(()=>{
let stream,recorder,chunks,micContext,micDestination;
const emit=(name,data={})=>window.__demoEvent(name,{browserTime:performance.now(),...data});
const get=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);
navigator.mediaDevices.getUserMedia=async c=>{if(!c.audio||c.video)return get(c);micContext??=new AudioContext({sampleRate:48000});await micContext.resume();micDestination=micContext.createMediaStreamDestination();const z=micContext.createConstantSource();z.offset.value=0;z.connect(micDestination);z.start();return micDestination.stream;};
window.__demoSpeak=async b=>{const a=Uint8Array.from(atob(b),c=>c.charCodeAt(0));const buffer=await micContext.decodeAudioData(a.buffer);const s=micContext.createBufferSource();s.buffer=buffer;s.connect(micDestination);s.connect(micContext.destination);s.start();return buffer.duration;};
window.__demoStartRecording=async(format)=>{
const ac=new AudioContext();await ac.resume();
stream=await navigator.mediaDevices.getDisplayMedia({video:{displaySurface:'browser',width:2560,height:1440,frameRate:30,cursor:'never'},audio:{suppressLocalAudioPlayback:false,echoCancellation:false,autoGainControl:false,noiseSuppression:false},preferCurrentTab:true,selfBrowserSurface:'include',systemAudio:'exclude'});
if(stream.getAudioTracks().length!==1||!stream.getAudioTracks()[0].getSettings().deviceId?.startsWith('web-contents-media-stream://'))throw Error('Expected tab playback audio');
chunks=[];recorder=new MediaRecorder(stream,{mimeType:format==='webm'?'video/webm;codecs=vp8,opus':'video/mp4;codecs=avc1.640033,mp4a.40.2',videoBitsPerSecond:24000000,audioBitsPerSecond:192000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.start(1000);emit('record-start');
// Alternate visual recording gets a longer warm-up and a small marker. Keep
// legacy MP4 calibration compatible with the existing reply-packaging scripts.
const alternate=format==='webm',pulse=alternate?1:.2;
await new Promise(r=>setTimeout(r,alternate?5000:600));const flash=document.createElement('div');flash.style.cssText='position:fixed;'+(alternate?'left:0;top:0;width:96px;height:96px;':'inset:0;')+'background:white;z-index:2147483647;transform:translateZ(0)';(document.getElementById('root')||document.body).append(flash);const tone=ac.createOscillator(),g=ac.createGain();g.gain.value=.12;tone.frequency.value=1000;tone.connect(g).connect(ac.destination);tone.start();tone.stop(ac.currentTime+pulse);await emit('calibration',{rect:flash.getBoundingClientRect().toJSON()});await new Promise(r=>setTimeout(r,pulse*1000));flash.remove();await new Promise(r=>setTimeout(r,1500));await ac.close();emit('usable-start');};
window.__demoStopRecording=()=>new Promise(resolve=>{emit('record-end');recorder.onstop=async()=>{const bytes=new Uint8Array(await new Blob(chunks).arrayBuffer());let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));stream.getTracks().forEach(t=>t.stop());resolve(btoa(s));};recorder.stop();});
addEventListener('DOMContentLoaded',()=>{const pointer=document.createElement('div');pointer.style.cssText='position:fixed;left:0;top:0;width:26px;height:32px;pointer-events:none;z-index:2147483646;filter:drop-shadow(0 2px 3px #3338)';pointer.innerHTML='<svg viewBox="0 0 26 32"><path d="M2 1L2 25L8 19L14 30L19 27L13 17L24 17Z" fill="white" stroke="#344c43" stroke-width="2"/></svg>';document.body.append(pointer);addEventListener('mousemove',e=>pointer.style.transform=`translate(${e.clientX}px,${e.clientY}px)`);addEventListener('pointerdown',e=>emit('click',{x:e.clientX,y:e.clientY,target:e.target.closest('button')?.getAttribute('aria-label')}));let last='';setInterval(()=>{const text=document.querySelector('.coach-conversation-list')?.innerText||'';if(text!==last){last=text;emit('chat',{text});}},100);});
})();
