import {writeFile} from 'node:fs/promises';
const call=async(path,data={})=>{const r=await fetch('http://127.0.0.1:8797/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const t=await r.text();if(!r.ok)throw Error(t);return t?JSON.parse(t):null;};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(test,label){const end=Date.now()+120000;while(Date.now()<end){const s=await call('status');if(test(s))return s;await delay(200);}throw Error(label+' timed out');}
const line='e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Bb3 Ba7 Nbd2 h6 Nf1 Be6 Ng3 Qd7 h3 Bxb3 axb3 Rfe8';
const q={id:'sofia-favourite',coach:'sofia',line,q:'What was my favourite chess tactic, and what should I look for to set one up?',context:'Fresh ConvaiClient with the same dedicated demo identity. No preference content appended to recall question or dynamicInfo.'};
await writeFile('edit/questions-v13-extra.json',JSON.stringify([q],null,2));
await call('prepare',{coach:'sofia',lines:{sofia:line},replay:false});await call('click',{name:'Open game library'});await call('click',{selector:'.games-list button:has-text("Sofia")'});await call('click',{name:'Resume game'});
await until(s=>s.canvas.length&&!s.text.includes('LOADING')&&s.text.includes('Your move — choose a piece.'),'ready');
await call('eval',{code:`(async()=>{const m=window.__demoManager,c=m.pool.get('sofia');await m.disconnectOne(c);window.__v13Identity={displayName:'Demo learner',endUserId:'chessbuddy-demo-v13-favourite-20260922',endUserMetadata:{}};m.syncEndUserIdentity(window.__v13Identity);await m.connectCoach(c.coach,{waitForBotReady:true,readyWaitMs:15000,endUserId:window.__v13Identity.endUserId,endUserMetadata:{}});return true;})()`});
const preference='My favourite tactic is a knight fork, especially when it checks the king and attacks the queen.';
await call('type',{name:'Ask Sofia',text:preference});await call('click',{name:'Send message'});await until(s=>s.text.includes('is speaking'),'preference response');await until(s=>s.text.includes('Your move — choose a piece.'),'preference complete');
const proof=await call('eval',{code:`(async()=>{const m=window.__demoManager,c=m.pool.get('sofia');const originalClient=c.client;const firstSession=c.client._characterSessionId;const saved=await m.rememberGameSummary(c.coach,'The student said their favourite chess tactic is a knight fork, especially checking the king and attacking the queen at the same time.');const listed=await c.client.memoryManager.listMemories();const matched=listed.memories.filter(x=>/favourite|favorite|knight fork/i.test(x.memory)).map(x=>({id:x.id,memory:x.memory}));await m.disconnectOne(c);await m.connectCoach(c.coach,{waitForBotReady:true,readyWaitMs:15000,endUserId:window.__v13Identity.endUserId,endUserMetadata:{}});return {saved,matched,firstSession,secondSession:c.client._characterSessionId,newClient:c.client!==originalClient,method:'Actual prior user utterance; persisted through app memory path; fresh client and generic recall question.'};})()`});
await writeFile('edit/v13-memory-proof.json',JSON.stringify({preference,...proof},null,2));console.log('MEMORY',JSON.stringify(proof));if(!proof.saved||!proof.newClient||!proof.matched.length)throw Error('Memory provenance failed');
await delay(1800);await call('record',{name:q.id+'-source'});await call('mha-start');await call('type',{name:'Ask Sofia',text:q.q});await call('click',{name:'Send message'});
await until(s=>s.text.includes('is speaking'),'recall response');await call('mark',{name:'speech-start'});await until(s=>s.text.includes('Your move — choose a piece.'),'recall complete');await call('mark',{name:'speech-end'});await delay(700);
const text=await call('eval',{code:"window.__demoManager.pool.get('sofia').longestResponseText"});await writeFile('capture/'+q.id+'-reply.json',JSON.stringify({...q,text},null,2));console.log(text);console.log(await call('mha-save',{name:q.id}));await call('stop');
