import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildMhaMeshMap } from './mhaToMorphMap';
import { CORRECTIVE_DEFS } from './mhaCorrectives';
import { BLINK_MORPHS } from './portraitBlink';

/**
 * scripts/optimize-coach-models.mjs strips every morph target that is not in
 * scripts/portrait-morph-keep.json. If the runtime lipsync/blink code starts
 * driving a morph that is missing from that list, the optimized GLBs silently
 * lose the shape. This test fails first.
 *
 * The list is generated by scripts/generate-morph-keep-list.mjs from the MHA
 * normalized-name matching over the assets-src models.
 */
describe('portrait-morph-keep.json', () => {
  const keepList: string[] = JSON.parse(
    readFileSync(join(__dirname, '..', 'scripts', 'portrait-morph-keep.json'), 'utf8'),
  ).keepMorphs;
  const keep = new Set(keepList);

  it('contains every C_* corrective morph in CORRECTIVE_DEFS', () => {
    const missing = CORRECTIVE_DEFS.map((def) => def[0]).filter((name) => !keep.has(name));
    expect(missing).toEqual([]);
  });

  it('contains the procedural blink morphs', () => {
    for (const name of BLINK_MORPHS) {
      expect(keep.has(name), name).toBe(true);
    }
  });

  it('every non-corrective entry is reachable by the MHA name matching', () => {
    const baseNames = keepList.filter((name) => !name.startsWith('C_'));
    const dict = Object.fromEntries(baseNames.map((name, i) => [name, i]));
    const map = buildMhaMeshMap(dict);
    const mappedSlots = new Set([...map.indexByMha].filter((slot) => slot >= 0));
    const unreachable = baseNames.filter((name) => !mappedSlots.has(dict[name]));
    expect(unreachable).toEqual([]);
  });

  it('has no duplicate entries', () => {
    expect(keepList.length).toBe(keep.size);
  });
});
