import { useSyncExternalStore } from 'react';
import {
  DEFAULT_THEME_ID,
  THEME_CHANGE_EVENT,
  normalizeThemeId,
  type ThemeId,
} from './theme';

export type ThemeCopy = Readonly<{
  productTitle: string;
  menuEyebrow: string;
  menuIntro: string;
  quickPlayLabel: string;
  quickPlayDescription: string;
  puzzlesLabel: string;
  puzzlesDescription: string;
  gamesLabel: string;
  gamesEmptyDescription: string;
  customCoachLabel: string;
  customCoachDescription: string;
  coachSetupLabel: string;
  skillSetupLabel: string;
  puzzleSetupLabel: string;
  quickPlayAction: string;
  puzzlesAction: string;
}>;

export const CLASSIC_THEME_COPY: ThemeCopy = {
  productTitle: 'Chessbuddy',
  menuEyebrow: 'Your personal chess coaching room',
  menuIntro: 'Play, practice, and review with a coach who sees the board with you.',
  quickPlayLabel: 'Play a Game',
  quickPlayDescription: 'Play a full match with live guidance when it matters',
  puzzlesLabel: 'Tactics',
  puzzlesDescription: 'Solve focused positions with progressive hints',
  gamesLabel: 'Game Library',
  gamesEmptyDescription: 'Review completed games and continue saved ones',
  customCoachLabel: 'Create a Coach',
  customCoachDescription: 'Shape a coaching style that fits how you learn',
  coachSetupLabel: 'Choose your coach',
  skillSetupLabel: 'Set the challenge',
  puzzleSetupLabel: 'Set the challenge',
  quickPlayAction: 'Start game',
  puzzlesAction: 'Start tactics',
};

/**
 * Presets opt into their own product voice one atomic redesign at a time.
 * Missing fields and presets inherit the accessible, complete Classic copy.
 */
export const THEME_COPY_OVERRIDES = {
  'flat-icon': {
    productTitle: 'Chess Shapes',
    menuEyebrow: 'A Playful Coaching Studio',
    menuIntro: 'Pick your guide, set the pace, and turn every position into a bright little lesson.',
    quickPlayLabel: 'Jump In',
    quickPlayDescription: 'A full match with friendly coaching as you play',
    puzzlesLabel: 'Tactics Playground',
    puzzlesDescription: 'Colourful challenges with hints when you need them',
    gamesLabel: 'Saved Boards',
    gamesEmptyDescription: 'Your played positions will collect here',
    customCoachLabel: 'Build a Guide',
    customCoachDescription: 'Shape a coach with a voice of your own',
    coachSetupLabel: 'Pick a Guide',
    skillSetupLabel: 'Choose Your Pace',
    puzzleSetupLabel: 'Puzzle Level',
    quickPlayAction: 'Start Playing',
    puzzlesAction: 'Open Puzzles',
  },
  'hand-drawn': {
    productTitle: 'The Chess Marginalia',
    menuEyebrow: 'An Annotated Playing Notebook',
    menuIntro: 'Choose a mentor, pencil in the challenge, and let every game leave a useful note in the margin.',
    quickPlayLabel: 'Begin a Study',
    quickPlayDescription: 'Play a complete game with live notes from your mentor',
    puzzlesLabel: 'Tactic Sketches',
    puzzlesDescription: 'Work through sharp positions one pencilled clue at a time',
    gamesLabel: 'Notebook Archive',
    gamesEmptyDescription: 'Finished studies and unfinished drafts will gather here',
    customCoachLabel: 'Draft a Mentor',
    customCoachDescription: 'Write a new teaching voice into the notebook',
    coachSetupLabel: 'Mentor in the Margin',
    skillSetupLabel: 'Study Depth',
    puzzleSetupLabel: 'Sketch Difficulty',
    quickPlayAction: 'Open a Fresh Board',
    puzzlesAction: 'Turn to the Exercises',
  },
  swiss: {
    productTitle: 'Schach Raster',
    menuEyebrow: 'International Play System',
    menuIntro: 'Select the instructor, calibrate the level, and approach every position with clarity, order, and purpose.',
    quickPlayLabel: 'Match Format',
    quickPlayDescription: 'One complete game with concise instruction in real time',
    puzzlesLabel: 'Tactical Module',
    puzzlesDescription: 'A structured sequence of positions, hints, and results',
    gamesLabel: 'Match Index',
    gamesEmptyDescription: 'Recorded games will appear in chronological order',
    customCoachLabel: 'Instructor Profile',
    customCoachDescription: 'Configure a teaching voice for your system',
    coachSetupLabel: 'Instructor',
    skillSetupLabel: 'Playing Standard',
    puzzleSetupLabel: 'Module Grade',
    quickPlayAction: 'Commence Match',
    puzzlesAction: 'Enter Module',
  },
  'art-deco': {
    productTitle: 'The Gilded Gambit',
    menuEyebrow: 'Private Salon · Evening Play',
    menuIntro: 'Invite a house master, choose the stakes, and settle in for an elegant contest under the brass lights.',
    quickPlayLabel: 'Salon Match',
    quickPlayDescription: 'A full evening game with discreet counsel between moves',
    puzzlesLabel: 'Brilliant Combinations',
    puzzlesDescription: 'Curated tactical set pieces from the club collection',
    gamesLabel: 'Match Ledger',
    gamesEmptyDescription: 'Your club fixtures will be entered here',
    customCoachLabel: 'Appoint a Master',
    customCoachDescription: 'Commission a distinctive voice for the salon',
    coachSetupLabel: 'House Master',
    skillSetupLabel: 'Table Stakes',
    puzzleSetupLabel: 'Combination Class',
    quickPlayAction: 'Take Your Seat',
    puzzlesAction: 'Enter the Salon',
  },
  newspaper: {
    productTitle: 'The Daily Knight',
    menuEyebrow: 'Chess Desk · Late Edition',
    menuIntro: 'Assign an editor, set the column grade, and make every move before the next edition goes to press.',
    quickPlayLabel: 'Lead Story',
    quickPlayDescription: 'Cover a complete match with live notes from the chess desk',
    puzzlesLabel: 'Problem Column',
    puzzlesDescription: 'Solve the day’s sharpest positions with graduated clues',
    gamesLabel: 'Morgue Archive',
    gamesEmptyDescription: 'Past editions and unfinished reports will be filed here',
    customCoachLabel: 'Hire a Columnist',
    customCoachDescription: 'Create a distinctive byline for analysis and advice',
    coachSetupLabel: 'Desk Editor',
    skillSetupLabel: 'Column Grade',
    puzzleSetupLabel: 'Problem Edition',
    quickPlayAction: 'Run the Story',
    puzzlesAction: 'Open Today’s Column',
  },
  'neo-brutalist': {
    productTitle: 'CHESS / HARD MOVE',
    menuEyebrow: 'NO POLISH. JUST POSITION.',
    menuIntro: 'Pick a voice. Set the pressure. Put the pieces down and prove the move works.',
    quickPlayLabel: 'FULL CONTACT',
    quickPlayDescription: 'One whole game with direct coaching and nowhere to hide',
    puzzlesLabel: 'TACTIC BLOCKS',
    puzzlesDescription: 'Hard positions, blunt hints, immediate results',
    gamesLabel: 'GAME STACK',
    gamesEmptyDescription: 'Played and unfinished games land here',
    customCoachLabel: 'BUILD A VOICE',
    customCoachDescription: 'Make a coach that says exactly what matters',
    coachSetupLabel: 'PICK YOUR CORNER',
    skillSetupLabel: 'SET THE PRESSURE',
    puzzleSetupLabel: 'BLOCK WEIGHT',
    quickPlayAction: 'DROP THE CLOCK',
    puzzlesAction: 'BREAK THE POSITION',
  },
  terminal: {
    productTitle: 'KNIGHT//SHELL',
    menuEyebrow: 'CHESS ENGINE OPERATOR CONSOLE',
    menuIntro: 'Mount a coach process, allocate search depth, and execute the next position from a clean prompt.',
    quickPlayLabel: 'RUN MATCH',
    quickPlayDescription: 'Start an interactive game session with live engine guidance',
    puzzlesLabel: 'TACTIC.EXE',
    puzzlesDescription: 'Process queued positions with staged diagnostic hints',
    gamesLabel: 'SESSION LOGS',
    gamesEmptyDescription: 'Completed and suspended sessions will be written here',
    customCoachLabel: 'COMPILE COACH',
    customCoachDescription: 'Configure and build a new guidance process',
    coachSetupLabel: 'ACTIVE PROCESS',
    skillSetupLabel: 'SEARCH DEPTH',
    puzzleSetupLabel: 'QUEUE LEVEL',
    quickPlayAction: 'EXECUTE SESSION',
    puzzlesAction: 'PROCESS QUEUE',
  },
  blueprint: {
    productTitle: 'The Knight Plan',
    menuEyebrow: 'Chessworks Drafting Office',
    menuIntro: 'Choose the lead architect, specify the playing load, and develop each position from first line to final move.',
    quickPlayLabel: 'Full Board Plan',
    quickPlayDescription: 'Draft a complete match with live structural review',
    puzzlesLabel: 'Position Schematics',
    puzzlesDescription: 'Resolve measured tactical studies with layered callouts',
    gamesLabel: 'Plan Archive',
    gamesEmptyDescription: 'Issued drawings and working revisions will be stored here',
    customCoachLabel: 'Design a Consultant',
    customCoachDescription: 'Specify a new voice for review and instruction',
    coachSetupLabel: 'Lead Architect',
    skillSetupLabel: 'Load Specification',
    puzzleSetupLabel: 'Drawing Scale',
    quickPlayAction: 'Issue the Plan',
    puzzlesAction: 'Open the Drawing Set',
  },
  risograph: {
    productTitle: 'Knight Ink Press',
    menuEyebrow: 'Two-Colour Chess Printshop',
    menuIntro: 'Choose the printmaker, mix the challenge, and pull a vivid new game through every layer of the board.',
    quickPlayLabel: 'Match Edition',
    quickPlayDescription: 'Print a complete game with live notes in every pass',
    puzzlesLabel: 'Spot-Ink Studies',
    puzzlesDescription: 'Layer bright tactical problems with one clue at a time',
    gamesLabel: 'Edition Shelf',
    gamesEmptyDescription: 'Proofs, editions, and unfinished runs will stack here',
    customCoachLabel: 'Cut a New Voice',
    customCoachDescription: 'Create a printmaker-coach with its own tone and rhythm',
    coachSetupLabel: 'Printmaker',
    skillSetupLabel: 'Ink Density',
    puzzleSetupLabel: 'Proof Grade',
    quickPlayAction: 'Pull the First Print',
    puzzlesAction: 'Run the Proof Sheet',
  },
  wooden: {
    productTitle: 'Walnut & Knight',
    menuEyebrow: 'The Cabinetmaker’s Chess Room',
    menuIntro: 'Select the resident player, choose the grain of the contest, and settle beside a hand-finished board.',
    quickPlayLabel: 'Club Table',
    quickPlayDescription: 'A full match with measured counsel across the baize',
    puzzlesLabel: 'Drawer Studies',
    puzzlesDescription: 'Hand-picked positions revealed from the problem cabinet',
    gamesLabel: 'Match Book',
    gamesEmptyDescription: 'Played fixtures and unfinished tables will be recorded here',
    customCoachLabel: 'Commission a Player',
    customCoachDescription: 'Craft a resident voice for the chess room',
    coachSetupLabel: 'Resident Player',
    skillSetupLabel: 'Playing Grain',
    puzzleSetupLabel: 'Cabinet Drawer',
    quickPlayAction: 'Set the Pieces',
    puzzlesAction: 'Unlock the Studies',
  },
  marble: {
    productTitle: 'The Quiet Gambit',
    menuEyebrow: 'Gallery of the Played Form',
    menuIntro: 'Choose the curator, set the room’s intensity, and consider each position as a composition in balance.',
    quickPlayLabel: 'Main Exhibition',
    quickPlayDescription: 'A complete match presented with quiet curatorial guidance',
    puzzlesLabel: 'Studies in Stone',
    puzzlesDescription: 'Contemplate selected tactical forms with restrained clues',
    gamesLabel: 'Collection Catalogue',
    gamesEmptyDescription: 'Past exhibitions and works in progress will appear here',
    customCoachLabel: 'Invite a Curator',
    customCoachDescription: 'Compose a refined new voice for the collection',
    coachSetupLabel: 'Gallery Curator',
    skillSetupLabel: 'Room Intensity',
    puzzleSetupLabel: 'Study Gallery',
    quickPlayAction: 'Enter the Exhibition',
    puzzlesAction: 'View the Studies',
  },
  'arcade-neon': {
    productTitle: 'KNIGHT FORCE ’88',
    menuEyebrow: 'INSERT CREDIT · CHESS CABINET',
    menuIntro: 'Choose your corner, set the stage speed, and chase the high score one electric move at a time.',
    quickPlayLabel: 'VERSUS MODE',
    quickPlayDescription: 'Battle through a full match with live corner coaching',
    puzzlesLabel: 'BONUS ROUND',
    puzzlesDescription: 'Clear rapid-fire tactic stages with unlockable hints',
    gamesLabel: 'HIGH SCORE RUNS',
    gamesEmptyDescription: 'Completed battles and continue points will appear here',
    customCoachLabel: 'CREATE PLAYER TWO',
    customCoachDescription: 'Build a new arcade rival with a signature voice',
    coachSetupLabel: 'SELECT FIGHTER',
    skillSetupLabel: 'STAGE SPEED',
    puzzleSetupLabel: 'BONUS STAGE',
    quickPlayAction: 'PRESS START',
    puzzlesAction: 'ENTER BONUS ROUND',
  },
  'frutiger-aero': {
    productTitle: 'BlueSky Chessway',
    menuEyebrow: 'A Living Network for Better Moves',
    menuIntro: 'Choose your guide, tune the learning climate, and follow a clear route through every growing position.',
    quickPlayLabel: 'Open Journey',
    quickPlayDescription: 'Play a full match with guidance flowing beside you',
    puzzlesLabel: 'Idea Springs',
    puzzlesDescription: 'Explore fresh tactical habitats with gentle layered hints',
    gamesLabel: 'Journey Map',
    gamesEmptyDescription: 'Completed routes and paused paths will bloom here',
    customCoachLabel: 'Grow a Guide',
    customCoachDescription: 'Shape a supportive new voice for your learning habitat',
    coachSetupLabel: 'Learning Guide',
    skillSetupLabel: 'Flow Level',
    puzzleSetupLabel: 'Habitat Depth',
    quickPlayAction: 'Follow the Blue Route',
    puzzlesAction: 'Explore the Springs',
  },
  'desktop-90s': {
    productTitle: 'KnightDesk 95',
    menuEyebrow: 'Chess Workbench for Home & Office',
    menuIntro: 'Choose an assistant, open the level control panel, and launch a new board from your desktop.',
    quickPlayLabel: 'Chess Program',
    quickPlayDescription: 'Open a full game window with coaching assistance',
    puzzlesLabel: 'Tactics Utility',
    puzzlesDescription: 'Run a set of position tools with step-by-step help',
    gamesLabel: 'Saved Documents',
    gamesEmptyDescription: 'Game files and suspended windows will be listed here',
    customCoachLabel: 'Assistant Manager',
    customCoachDescription: 'Install and configure a new coaching profile',
    coachSetupLabel: 'Desktop Assistant',
    skillSetupLabel: 'Performance Setting',
    puzzleSetupLabel: 'Utility Level',
    quickPlayAction: 'Launch Chess',
    puzzlesAction: 'Run Tactics Utility',
  },
  editorial: {
    productTitle: 'Knight / Form',
    menuEyebrow: 'The Independent Journal of Chess',
    menuIntro: 'Choose the contributing master, set the issue’s intensity, and compose a game worthy of the closing spread.',
    quickPlayLabel: 'Cover Feature',
    quickPlayDescription: 'A complete match shaped by live editorial insight',
    puzzlesLabel: 'Tactical Portfolio',
    puzzlesDescription: 'A curated edit of striking positions and considered clues',
    gamesLabel: 'Issue Archive',
    gamesEmptyDescription: 'Published matches and works in progress will collect here',
    customCoachLabel: 'Commission a Voice',
    customCoachDescription: 'Develop a distinctive contributor for the journal',
    coachSetupLabel: 'Contributing Master',
    skillSetupLabel: 'Issue Intensity',
    puzzleSetupLabel: 'Portfolio Edit',
    quickPlayAction: 'Begin the Sitting',
    puzzlesAction: 'View the Portfolio',
  },
  'cyberpunk-hud': {
    productTitle: 'NIGHTGRID // CHESS',
    menuEyebrow: 'LIVE TACTICAL COMMAND OVERLAY',
    menuIntro: 'Select an operator, assign the threat tier, and deploy into a board where every move updates the grid.',
    quickPlayLabel: 'LIVE OPERATION',
    quickPlayDescription: 'Run a full engagement with real-time tactical telemetry',
    puzzlesLabel: 'BREACH SIMULATIONS',
    puzzlesDescription: 'Resolve hostile positions with escalating intel reveals',
    gamesLabel: 'MISSION DOSSIERS',
    gamesEmptyDescription: 'Closed operations and suspended deployments will appear here',
    customCoachLabel: 'BUILD AN OPERATOR',
    customCoachDescription: 'Configure a new tactical voice for the network',
    coachSetupLabel: 'FIELD OPERATOR',
    skillSetupLabel: 'THREAT TIER',
    puzzleSetupLabel: 'SIMULATION CLASS',
    quickPlayAction: 'DEPLOY TO GRID',
    puzzlesAction: 'RUN BREACH SIM',
  },
  'japanese-minimal': {
    productTitle: 'Chessbuddy',
    menuEyebrow: 'Your personal chess coaching room',
    menuIntro: 'Play, practice, and review with a coach who sees the board with you.',
    quickPlayLabel: 'Play a Game',
    quickPlayDescription: 'Play a full match with live guidance when it matters',
    puzzlesLabel: 'Tactics',
    puzzlesDescription: 'Solve focused positions with progressive hints',
    gamesLabel: 'Game Library',
    gamesEmptyDescription: 'Review completed games and continue saved ones',
    customCoachLabel: 'Create a Coach',
    customCoachDescription: 'Shape a coaching style that fits how you learn',
    coachSetupLabel: 'Choose your coach',
    skillSetupLabel: 'Set the challenge',
    puzzleSetupLabel: 'Set the challenge',
    quickPlayAction: 'Start game',
    puzzlesAction: 'Start tactics',
  },
  'stained-glass': {
    productTitle: 'Lumen Boardworks',
    menuEyebrow: 'A Vaulted Gallery of Light and Play',
    menuIntro: 'Choose the glass artist, set the brilliance, and let each move reshape the colour passing through the board.',
    quickPlayLabel: 'Grand Light Panel',
    quickPlayDescription: 'Compose a complete match through luminous guidance',
    puzzlesLabel: 'Glasswork Studies',
    puzzlesDescription: 'Resolve jewel-toned positions through layered light cues',
    gamesLabel: 'Panel Collection',
    gamesEmptyDescription: 'Finished panels and works in progress will be displayed here',
    customCoachLabel: 'Design a Glass Artist',
    customCoachDescription: 'Create a new voice for colour, structure, and play',
    coachSetupLabel: 'Glass Artist',
    skillSetupLabel: 'Light Intensity',
    puzzleSetupLabel: 'Panel Complexity',
    quickPlayAction: 'Illuminate the Board',
    puzzlesAction: 'Enter the Light Gallery',
  },
  bauhaus: {
    productTitle: 'Formspiel 64',
    menuEyebrow: 'A Workshop for Form, Function, and Play',
    menuIntro: 'Select a workshop master, calibrate the challenge, and build each position from clear geometry and purposeful moves.',
    quickPlayLabel: 'The Complete Study',
    quickPlayDescription: 'Construct a full match with direct, functional guidance',
    puzzlesLabel: 'Form Exercises',
    puzzlesDescription: 'Solve geometric positions through ordered visual prompts',
    gamesLabel: 'Works Register',
    gamesEmptyDescription: 'Completed studies and active constructions will be catalogued here',
    customCoachLabel: 'Draft a Workshop Master',
    customCoachDescription: 'Develop a clear-minded voice for structure and practical play',
    coachSetupLabel: 'Workshop Master',
    skillSetupLabel: 'Functional Grade',
    puzzleSetupLabel: 'Exercise Series',
    quickPlayAction: 'Set the Forms in Motion',
    puzzlesAction: 'Open the Exercise Folio',
  },
  'soft-clay': {
    productTitle: 'Mallow & Move',
    menuEyebrow: 'A Tactile Studio for Soft-Form Strategy',
    menuIntro: 'Choose a playmaker, tune the bounce, and shape a match from rounded pieces, gentle cues, and satisfying decisions.',
    quickPlayLabel: 'Tabletop Playset',
    quickPlayDescription: 'Settle into a full match with warm, hands-on guidance',
    puzzlesLabel: 'Pocket-Sized Problems',
    puzzlesDescription: 'Press through sculpted positions with soft hints',
    gamesLabel: 'Toy Shelf',
    gamesEmptyDescription: 'Finished playsets and paused builds will be arranged here',
    customCoachLabel: 'Mould a Playmaker',
    customCoachDescription: 'Shape a companion with a voice all their own',
    coachSetupLabel: 'Playmaker',
    skillSetupLabel: 'Bounce Level',
    puzzleSetupLabel: 'Moulding Detail',
    quickPlayAction: 'Bring the Board to Life',
    puzzlesAction: 'Open the Puzzle Box',
  },
  'solarpunk-conservatory': {
    productTitle: 'The Verdant Circuit',
    menuEyebrow: 'A Living Conservatory for Future Play',
    menuIntro: 'Choose a steward, balance the system, and grow a match where sunlight, strategy, and responsive tools work together.',
    quickPlayLabel: 'Living Match Cycle',
    quickPlayDescription: 'Cultivate a complete game with adaptive guidance in bloom',
    puzzlesLabel: 'Canopy Experiments',
    puzzlesDescription: 'Restore intricate positions with renewable hints',
    gamesLabel: 'Seed Archive',
    gamesEmptyDescription: 'Matured matches and dormant sessions will take root here',
    customCoachLabel: 'Cultivate a Steward',
    customCoachDescription: 'Grow a new guiding voice for resilient, imaginative play',
    coachSetupLabel: 'Conservatory Steward',
    skillSetupLabel: 'Ecosystem Balance',
    puzzleSetupLabel: 'Growth Conditions',
    quickPlayAction: 'Open the Sunward Board',
    puzzlesAction: 'Enter the Propagation Lab',
  },
  'noir-detective': {
    productTitle: 'The Black Knight Files',
    menuEyebrow: 'Private Strategy Bureau · Cases Open After Dark',
    menuIntro: 'Choose your investigator, assess the risk, and work the board until every motive, threat, and missing move comes to light.',
    quickPlayLabel: 'Open Case',
    quickPlayDescription: 'Follow a complete match with incisive field observations',
    puzzlesLabel: 'Cold Case Desk',
    puzzlesDescription: 'Reconstruct difficult positions from carefully released evidence',
    gamesLabel: 'Case Archive',
    gamesEmptyDescription: 'Closed investigations and active files will be stored here',
    customCoachLabel: 'Recruit an Investigator',
    customCoachDescription: 'Define a new analytical voice for difficult cases',
    coachSetupLabel: 'Lead Investigator',
    skillSetupLabel: 'Case Risk',
    puzzleSetupLabel: 'Evidence Access',
    quickPlayAction: 'Take the Case',
    puzzlesAction: 'Examine the Evidence',
  },
  'cosmic-observatory': {
    productTitle: 'Asterion Move Atlas',
    menuEyebrow: 'Deep-Sky Observatory · Strategic Survey',
    menuIntro: 'Choose an astronomer, calibrate the instruments, and chart a game across a board of shifting paths and distant possibilities.',
    quickPlayLabel: 'Full Observation Run',
    quickPlayDescription: 'Track an entire match with live orbital analysis',
    puzzlesLabel: 'Celestial Anomalies',
    puzzlesDescription: 'Resolve rare tactical alignments from measured signal clues',
    gamesLabel: 'Observation Log',
    gamesEmptyDescription: 'Completed surveys and suspended trajectories will be recorded here',
    customCoachLabel: 'Appoint an Astronomer',
    customCoachDescription: 'Configure a new voice for patient, far-reaching analysis',
    coachSetupLabel: 'Observatory Astronomer',
    skillSetupLabel: 'Instrument Range',
    puzzleSetupLabel: 'Signal Depth',
    quickPlayAction: 'Begin the Night Survey',
    puzzlesAction: 'Plot the Anomalies',
  },
  'royal-opera': {
    productTitle: 'The Grand Knight Theatre',
    menuEyebrow: 'An Opera House for Strategy in Full Voice',
    menuIntro: 'Choose a principal, set the dramatic register, and stage a match where every entrance, sacrifice, and finale earns its moment.',
    quickPlayLabel: 'Evening Performance',
    quickPlayDescription: 'Present a complete match with insight from the wings',
    puzzlesLabel: 'Rehearsal Scenes',
    puzzlesDescription: 'Perfect demanding positions through carefully timed prompts',
    gamesLabel: 'Repertoire Ledger',
    gamesEmptyDescription: 'Past performances and paused productions will be listed here',
    customCoachLabel: 'Cast a New Principal',
    customCoachDescription: 'Shape a commanding voice for the next production',
    coachSetupLabel: 'Principal Artist',
    skillSetupLabel: 'Dramatic Register',
    puzzleSetupLabel: 'Rehearsal Act',
    quickPlayAction: 'Raise the Curtain',
    puzzlesAction: 'Call the Rehearsal',
  },
  'library-at-midnight': {
    productTitle: 'The Nocturne Athenaeum',
    menuEyebrow: 'Rare Games Reading Room · Open Past Midnight',
    menuIntro: 'Choose a curator, request the appropriate collection, and study a game beneath the lamps while the rest of the stacks sleep.',
    quickPlayLabel: 'Night Reading',
    quickPlayDescription: 'Settle into a complete match with discerning marginal notes',
    puzzlesLabel: 'Restricted Folios',
    puzzlesDescription: 'Interpret uncommon positions through gradually unsealed annotations',
    gamesLabel: 'Private Catalogue',
    gamesEmptyDescription: 'Finished readings and bookmarked sessions will be indexed here',
    customCoachLabel: 'Invite a Guest Curator',
    customCoachDescription: 'Establish a learned new voice for the reading room',
    coachSetupLabel: 'Collection Curator',
    skillSetupLabel: 'Reading Level',
    puzzleSetupLabel: 'Archive Access',
    quickPlayAction: 'Request the Reading Table',
    puzzlesAction: 'Unseal the Folios',
  },
  'mediterranean-ceramic': {
    productTitle: 'Azul Mare Atelier',
    menuEyebrow: 'A Coastal Workshop of Glaze, Pattern, and Play',
    menuIntro: 'Choose a ceramicist, set the firing profile, and compose a match from sea-bright colour, deliberate pattern, and patient craft.',
    quickPlayLabel: 'Signature Tile Set',
    quickPlayDescription: 'Lay out a complete game with practiced studio guidance',
    puzzlesLabel: 'Kiln-Side Studies',
    puzzlesDescription: 'Complete intricate positions from carefully revealed pattern marks',
    gamesLabel: 'Atelier Shelves',
    gamesEmptyDescription: 'Fired sets and unfinished arrangements will be displayed here',
    customCoachLabel: 'Commission a Ceramicist',
    customCoachDescription: 'Form a distinctive studio voice for colour and composition',
    coachSetupLabel: 'Master Ceramicist',
    skillSetupLabel: 'Firing Profile',
    puzzleSetupLabel: 'Tessellation Detail',
    quickPlayAction: 'Set the Tile Table',
    puzzlesAction: 'Enter the Glaze Room',
  },
  'botanical-engraving': {
    productTitle: 'Knightwort Field Folio',
    menuEyebrow: 'Natural History Print Room · Strategic Specimens',
    menuIntro: 'Choose a field naturalist, set the observation scale, and examine a game where every variation branches with purpose.',
    quickPlayLabel: 'Complete Field Study',
    quickPlayDescription: 'Document a full match with precise observational notes',
    puzzlesLabel: 'Specimen Plates',
    puzzlesDescription: 'Identify tactical structures from progressively labelled details',
    gamesLabel: 'Herbarium Register',
    gamesEmptyDescription: 'Pressed matches and unfinished surveys will be filed here',
    customCoachLabel: 'Name a Field Naturalist',
    customCoachDescription: 'Describe a discerning new voice for close observation',
    coachSetupLabel: 'Field Naturalist',
    skillSetupLabel: 'Observation Scale',
    puzzleSetupLabel: 'Plate Annotation',
    quickPlayAction: 'Open the Field Folio',
    puzzlesAction: 'Inspect the Specimens',
  },
  'memphis-pop': {
    productTitle: 'Squiggle Strategy Works',
    menuEyebrow: 'A Postmodern Playground for Serious Moves',
    menuIntro: 'Choose a design provocateur, dial up the pattern clash, and build a match where wit, geometry, and bold decisions share the table.',
    quickPlayLabel: 'Statement Piece',
    quickPlayDescription: 'Play a complete match with spirited creative direction',
    puzzlesLabel: 'Shape Experiments',
    puzzlesDescription: 'Solve offbeat positions through punchy graphic prompts',
    gamesLabel: 'Prototype Rack',
    gamesEmptyDescription: 'Finished statements and paused experiments will collect here',
    customCoachLabel: 'Invent a Design Provocateur',
    customCoachDescription: 'Give a fearless new voice to colour, wit, and strategy',
    coachSetupLabel: 'Design Provocateur',
    skillSetupLabel: 'Pattern Clash',
    puzzleSetupLabel: 'Shape Mix',
    quickPlayAction: 'Make the First Statement',
    puzzlesAction: 'Scatter the Shapes',
  },
  'desert-modernism': {
    productTitle: 'The Suncourt Gambit',
    menuEyebrow: 'A Desert House for Spatial Strategy',
    menuIntro: 'Choose an architect, set the sun exposure, and compose a match through shaded courtyards, long sightlines, and purposeful restraint.',
    quickPlayLabel: 'Courtyard Session',
    quickPlayDescription: 'Play a complete game with measured spatial guidance',
    puzzlesLabel: 'Sun-Path Studies',
    puzzlesDescription: 'Resolve spare positions through precisely placed cues',
    gamesLabel: 'House Portfolio',
    gamesEmptyDescription: 'Completed sessions and unfinished schemes will rest here',
    customCoachLabel: 'Engage a Desert Architect',
    customCoachDescription: 'Define a composed new voice for space and strategy',
    coachSetupLabel: 'Project Architect',
    skillSetupLabel: 'Sun Exposure',
    puzzleSetupLabel: 'Spatial Density',
    quickPlayAction: 'Open the Courtyard',
    puzzlesAction: 'Trace the Sun Paths',
  },
  'oceanic-biome': {
    productTitle: 'Pelagic Strategy Station',
    menuEyebrow: 'An Underwater Habitat for Deep-Current Play',
    menuIntro: 'Choose a marine researcher, set the dive range, and navigate a match through changing currents, living systems, and hidden depth.',
    quickPlayLabel: 'Full Transect Dive',
    quickPlayDescription: 'Survey a complete game with real-time habitat guidance',
    puzzlesLabel: 'Reef Anomalies',
    puzzlesDescription: 'Resolve submerged positions from sequenced sonar readings',
    gamesLabel: 'Dive Log',
    gamesEmptyDescription: 'Completed transects and suspended missions will surface here',
    customCoachLabel: 'Assign a Marine Researcher',
    customCoachDescription: 'Configure a perceptive new voice for dynamic systems',
    coachSetupLabel: 'Marine Researcher',
    skillSetupLabel: 'Dive Range',
    puzzleSetupLabel: 'Sonar Resolution',
    quickPlayAction: 'Flood the Observation Deck',
    puzzlesAction: 'Scan the Reef',
  },
  'alpine-lodge': {
    productTitle: 'The High Pass Chess Room',
    menuEyebrow: 'A Mountain Lodge for Clear-Headed Play',
    menuIntro: 'Choose a route guide, read the weather window, and settle into a match shaped by long views, warm timber, and decisive turns.',
    quickPlayLabel: 'Hearthside Match',
    quickPlayDescription: 'Play a complete game with steady guidance from the lodge',
    puzzlesLabel: 'Summit Routes',
    puzzlesDescription: 'Navigate demanding positions through staged route markers',
    gamesLabel: 'Expedition Ledger',
    gamesEmptyDescription: 'Completed crossings and paused ascents will be entered here',
    customCoachLabel: 'Choose a Route Guide',
    customCoachDescription: 'Create a sure-footed new voice for difficult terrain',
    coachSetupLabel: 'Alpine Guide',
    skillSetupLabel: 'Weather Window',
    puzzleSetupLabel: 'Route Exposure',
    quickPlayAction: 'Take the Hearth Table',
    puzzlesAction: 'Plan the Ascent',
  },
  'candy-kawaii': {
    productTitle: 'Bonbon Knight Parade',
    menuEyebrow: 'A Character Confectionery for Delightful Strategy',
    menuIntro: 'Choose a confectioner mascot, pick the flavour level, and unwrap a match filled with bright personalities and clever surprises.',
    quickPlayLabel: 'Deluxe Bonbon Box',
    quickPlayDescription: 'Enjoy a complete game with cheerful character guidance',
    puzzlesLabel: 'Sugar-Spark Challenges',
    puzzlesDescription: 'Crack charming positions with tiny treats of insight',
    gamesLabel: 'Sweet Storybook',
    gamesEmptyDescription: 'Finished adventures and saved little chapters will appear here',
    customCoachLabel: 'Create a Confectioner Mascot',
    customCoachDescription: 'Dream up a bright new personality for playful strategy',
    coachSetupLabel: 'Confectioner Mascot',
    skillSetupLabel: 'Flavour Level',
    puzzleSetupLabel: 'Surprise Filling',
    quickPlayAction: 'Unwrap the Match',
    puzzlesAction: 'Open the Treat Drawer',
  },
  'lunar-colony': {
    productTitle: 'Mare Tranquillitatis Chess Control',
    menuEyebrow: 'Lunar Surface Operations · Strategy Habitat',
    menuIntro: 'Choose a mission controller, set the surface window, and direct a match across silent sectors where every resource and route matters.',
    quickPlayLabel: 'Surface Operation',
    quickPlayDescription: 'Run a complete game with measured habitat telemetry',
    puzzlesLabel: 'Regolith Scenarios',
    puzzlesDescription: 'Resolve isolated positions through staged sensor packets',
    gamesLabel: 'Habitat Mission Log',
    gamesEmptyDescription: 'Completed sorties and suspended surface plans will be recorded here',
    customCoachLabel: 'Assign a Mission Controller',
    customCoachDescription: 'Configure a precise new voice for remote operations',
    coachSetupLabel: 'Mission Controller',
    skillSetupLabel: 'Surface Window',
    puzzleSetupLabel: 'Sensor Fidelity',
    quickPlayAction: 'Authorize Surface Play',
    puzzlesAction: 'Load the Regolith Scenarios',
  },
  'persian-miniature': {
    productTitle: 'The Azure Garden Album',
    menuEyebrow: 'An Illuminated Atelier of Pattern and Play',
    menuIntro: 'Choose an album painter, set the brushwork detail, and compose a match through balanced gardens, fine colour, and attentive storytelling.',
    quickPlayLabel: 'Illuminated Encounter',
    quickPlayDescription: 'Render a complete game with considered guidance beside each turn',
    puzzlesLabel: 'Painted Stratagems',
    puzzlesDescription: 'Read intricate positions through details revealed across the composition',
    gamesLabel: 'Album Leaves',
    gamesEmptyDescription: 'Completed encounters and unfinished paintings will be gathered here',
    customCoachLabel: 'Invite an Album Painter',
    customCoachDescription: 'Compose a thoughtful new voice for pattern and narrative',
    coachSetupLabel: 'Atelier Painter',
    skillSetupLabel: 'Pigment Depth',
    puzzleSetupLabel: 'Border Intricacy',
    quickPlayAction: 'Begin the Painted Game',
    puzzlesAction: 'Turn to the Study Leaves',
  },
  'vaporwave-dream': {
    productTitle: 'The Afterimage Channel',
    menuEyebrow: 'A Late-Night Transmission from Somewhere Familiar',
    menuIntro: 'Choose a dreamcaster, tune the memory frequency, and drift into a match carried by soft signals, distant plazas, and endless sunset.',
    quickPlayLabel: 'Feature Transmission',
    quickPlayDescription: 'Receive a complete game with commentary from beyond the dial',
    puzzlesLabel: 'Signal Fragments',
    puzzlesDescription: 'Reassemble uncanny positions from slowly clearing interference',
    gamesLabel: 'Tape Archive',
    gamesEmptyDescription: 'Recorded transmissions and paused reveries will loop here',
    customCoachLabel: 'Create a Dreamcaster',
    customCoachDescription: 'Shape a new broadcast voice from mood and memory',
    coachSetupLabel: 'Dreamcaster',
    skillSetupLabel: 'Memory Frequency',
    puzzleSetupLabel: 'Signal Distortion',
    quickPlayAction: 'Tune Into the Match',
    puzzlesAction: 'Recover the Fragments',
  },
  'dark-academia': {
    productTitle: 'The Rook & Reason Society',
    menuEyebrow: 'A Collegium for Argument, Analysis, and Play',
    menuIntro: 'Choose an interlocutor, set the seminar rigor, and test each position through claim, counterclaim, and disciplined inquiry.',
    quickPlayLabel: 'Board Colloquium',
    quickPlayDescription: 'Conduct a complete match with rigorous commentary and reply',
    puzzlesLabel: 'Problems for Disputation',
    puzzlesDescription: 'Defend difficult conclusions through structured annotations',
    gamesLabel: 'Society Proceedings',
    gamesEmptyDescription: 'Concluded arguments and adjourned sessions will be entered here',
    customCoachLabel: 'Appoint an Interlocutor',
    customCoachDescription: 'Establish a distinctive voice for inquiry and rebuttal',
    coachSetupLabel: 'Seminar Interlocutor',
    skillSetupLabel: 'Argument Rigor',
    puzzleSetupLabel: 'Annotation Density',
    quickPlayAction: 'Convene the Board',
    puzzlesAction: 'Open the Disputation',
  },
  'pop-art-comic': {
    productTitle: 'CHECK! The Illustrated Clash',
    menuEyebrow: 'A Bold-Faced Serial of Moves, Mischief, and Momentum',
    menuIntro: 'Choose a panel editor, set the dramatic stakes, and ink a showdown where every turn deserves a headline and every reversal lands.',
    quickPlayLabel: 'Lead Story Showdown',
    quickPlayDescription: 'Stage a complete confrontation with commentary between panels',
    puzzlesLabel: 'Cliffhanger Cases',
    puzzlesDescription: 'Crack explosive positions through reveals timed like page turns',
    gamesLabel: 'Back-Issue Box',
    gamesEmptyDescription: 'Finished showdowns and stories awaiting an ending will stack here',
    customCoachLabel: 'Create a Panel Editor',
    customCoachDescription: 'Write a quick-witted new voice for action and reversal',
    coachSetupLabel: 'Panel Editor',
    skillSetupLabel: 'Dramatic Stakes',
    puzzleSetupLabel: 'Reveal Timing',
    quickPlayAction: 'Ink the Opening Panel',
    puzzlesAction: 'Turn the Cliffhanger Page',
  },
  'nordic-frost': {
    productTitle: 'Northlight Route Institute',
    menuEyebrow: 'Polar Navigation Laboratory · Clear Decisions Ahead',
    menuIntro: 'Choose a route analyst, assess the light conditions, and map a match across open terrain where precision keeps every path legible.',
    quickPlayLabel: 'Polar Survey Route',
    quickPlayDescription: 'Chart a complete game with concise field guidance',
    puzzlesLabel: 'Whiteout Exercises',
    puzzlesDescription: 'Recover critical paths from controlled visibility readings',
    gamesLabel: 'Survey Chartroom',
    gamesEmptyDescription: 'Completed crossings and routes under review will be mapped here',
    customCoachLabel: 'Assign a Route Analyst',
    customCoachDescription: 'Define a clear new voice for weather, distance, and decision',
    coachSetupLabel: 'Route Analyst',
    skillSetupLabel: 'Light Conditions',
    puzzleSetupLabel: 'Visibility Range',
    quickPlayAction: 'Set the Northward Course',
    puzzlesAction: 'Enter the Whiteout Lab',
  },
  'tropical-resort': {
    productTitle: 'The Canopy Gambit Club',
    menuEyebrow: 'A Private Strategy Retreat Beyond the Everyday',
    menuIntro: 'Choose a resident host, select the pace of stay, and settle into a match planned around shaded pavilions, open air, and unhurried focus.',
    quickPlayLabel: 'Pavilion Match',
    quickPlayDescription: 'Enjoy a complete game with attentive resort-side guidance',
    puzzlesLabel: 'Garden Itineraries',
    puzzlesDescription: 'Explore curated positions with clues revealed along the route',
    gamesLabel: 'Guest Journal',
    gamesEmptyDescription: 'Completed stays and paused itineraries will be noted here',
    customCoachLabel: 'Appoint a Resident Host',
    customCoachDescription: 'Create a gracious new voice for focused leisure',
    coachSetupLabel: 'Resident Host',
    skillSetupLabel: 'Pace of Stay',
    puzzleSetupLabel: 'Itinerary Detail',
    quickPlayAction: 'Check In to the Pavilion',
    puzzlesAction: 'Follow the Garden Route',
  },
  'kinetic-chrome': {
    productTitle: 'Vectorforge Motion Works',
    menuEyebrow: 'An Articulated Instrument for Strategy in Motion',
    menuIntro: 'Choose a motion engineer, calibrate the torque profile, and drive a match through precise vectors, responsive surfaces, and controlled momentum.',
    quickPlayLabel: 'Full Motion Cycle',
    quickPlayDescription: 'Run a complete game with live mechanical response analysis',
    puzzlesLabel: 'Vector Stress Tests',
    puzzlesDescription: 'Resolve loaded positions through sequenced force readings',
    gamesLabel: 'Performance Registry',
    gamesEmptyDescription: 'Completed cycles and suspended assemblies will be logged here',
    customCoachLabel: 'Configure a Motion Engineer',
    customCoachDescription: 'Build a precise new voice for force, material, and response',
    coachSetupLabel: 'Motion Engineer',
    skillSetupLabel: 'Torque Profile',
    puzzleSetupLabel: 'Vector Load',
    quickPlayAction: 'Engage the Motion Array',
    puzzlesAction: 'Run the Stress Sequence',
  },
} as const satisfies Partial<Record<ThemeId, Partial<ThemeCopy>>>;

export function getThemeCopy(themeId: ThemeId): ThemeCopy {
  return {
    ...CLASSIC_THEME_COPY,
    ...THEME_COPY_OVERRIDES[themeId as keyof typeof THEME_COPY_OVERRIDES],
  };
}

function readActiveTheme(): ThemeId {
  if (typeof document === 'undefined') return DEFAULT_THEME_ID;
  return normalizeThemeId(document.documentElement.dataset.theme);
}

function subscribeToThemeChange(onStoreChange: () => void): () => void {
  if (typeof window === 'undefined') return () => {};
  window.addEventListener(THEME_CHANGE_EVENT, onStoreChange);
  return () => window.removeEventListener(THEME_CHANGE_EVENT, onStoreChange);
}

export function useThemeCopy(): ThemeCopy {
  const themeId = useSyncExternalStore(
    subscribeToThemeChange,
    readActiveTheme,
    () => DEFAULT_THEME_ID,
  );
  return getThemeCopy(themeId);
}
